# Generated by Django 5.2.4 on 2025-10-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gattest',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gat_tests', to='core.quarter', verbose_name='Четверть'),
        ),
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number_of_questions', models.PositiveIntegerField(default=10, verbose_name='Количество вопросов')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_counts', to='core.schoolclass', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_counts', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Количество вопросов',
                'verbose_name_plural': 'Количества вопросов',
                'ordering': ['school_class__school__name', 'school_class__name', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'subject'), name='unique_question_count_per_class_subject')],
            },
        ),
    ]
