# Generated by Django 5.2.6 on 2025-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='gat_info',
            field=models.CharField(blank=True, help_text='Для какого GAT предназначен этот предмет (просто информация)', max_length=100),
        ),
    ]
