# Generated by Django 5.2.4 on 2025-10-22 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа (Банк)',
                'verbose_name_plural': 'Варианты ответа (Банк)',
                'ordering': ['question', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('MCQ', 'Один правильный ответ')], default='MCQ', max_length=10, verbose_name='Тип вопроса')),
                ('difficulty', models.CharField(choices=[('EASY', 'Легкий'), ('MEDIUM', 'Средний'), ('HARD', 'Сложный')], default='MEDIUM', max_length=10, verbose_name='Сложность')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги для поиска')),
            ],
            options={
                'verbose_name': 'Вопрос из Банка',
                'verbose_name_plural': 'Вопросы из Банка',
                'ordering': ['topic', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема вопросов',
                'verbose_name_plural': 'Темы вопросов',
                'ordering': ['subject__name', 'school_class__name', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='answeroption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gat_test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['result', 'question__topic'], 'verbose_name': 'Ответ ученика (Банк)', 'verbose_name_plural': 'Ответы учеников (Банк)'},
        ),
        migrations.RemoveConstraint(
            model_name='studentanswer',
            name='unique_answer_per_result_question',
        ),
        migrations.RemoveField(
            model_name='gattest',
            name='subjects',
        ),
        migrations.AddField(
            model_name='gattest',
            name='shuffle_options',
            field=models.BooleanField(default=False, verbose_name='Перемешивать варианты?'),
        ),
        migrations.AddField(
            model_name='gattest',
            name='shuffle_questions',
            field=models.BooleanField(default=False, verbose_name='Перемешивать вопросы?'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='chosen_option_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок выбранного варианта'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='booklet_variant',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Вариант Буклета'),
        ),
        migrations.AlterField(
            model_name='gattest',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.school', verbose_name='Школа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gattest',
            name='school_class',
            field=models.ForeignKey(default=1, limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.schoolclass', verbose_name='Класс (Параллель)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questioncount',
            name='school_class',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='question_counts', to='core.schoolclass', verbose_name='Класс (Параллель)'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='school_class',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_questions', to='core.schoolclass', verbose_name='Класс (Параллель)'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_questions', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='bankansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.bankquestion', verbose_name='Вопрос из Банка'),
        ),
        migrations.AddField(
            model_name='gattest',
            name='questions',
            field=models.ManyToManyField(related_name='gat_tests', to='core.bankquestion', verbose_name='Вопросы из Банка'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.bankquestion', verbose_name='Вопрос из Банка'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('result', 'question'), name='unique_answer_per_result_bank_question'),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='school_class',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.schoolclass', verbose_name='Класс (Параллель)'),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questiontopic', verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddConstraint(
            model_name='questiontopic',
            constraint=models.UniqueConstraint(fields=('subject', 'school_class', 'name'), name='unique_topic_per_subject_class'),
        ),
    ]
