# Generated by Django 5.2.4 on 2025-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gattest_quarter_questioncount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gattest',
            name='school',
        ),
        migrations.AddField(
            model_name='gattest',
            name='school_classes',
            field=models.ManyToManyField(related_name='gat_tests', to='core.schoolclass', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='gattest',
            name='test_number',
            field=models.PositiveIntegerField(choices=[(1, 'GAT-1'), (2, 'GAT-2')], verbose_name='Номер GAT'),
        ),
    ]
