# Generated by Django 5.2.6 on 2025-09-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_gat_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='core.schoolclass'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='Полное название класса, например: 5А или 10', max_length=10),
        ),
    ]
