# Generated by Django 5.2.4 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bankansweroption_bankquestion_questiontopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankansweroption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='Изображение к варианту'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение к вопросу'),
        ),
    ]
