# Generated by Django 5.2.4 on 2025-11-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bankansweroption_option_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gattest',
            name='question_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Порядок вопросов'),
        ),
    ]
