# Generated by Django 5.2.4 on 2025-10-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gattest_school_gattest_school_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gattest',
            name='school_classes',
        ),
        migrations.RemoveField(
            model_name='gattest',
            name='subjects',
        ),
        migrations.AddField(
            model_name='gattest',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='gattest',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.schoolclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='gattest',
            name='test_number',
            field=models.PositiveIntegerField(choices=[(1, 'GAT-1'), (2, 'GAT-2'), (3, 'GAT-3'), (4, 'GAT-4')], verbose_name='Номер GAT'),
        ),
    ]
