# Generated by Django 5.2.4 on 2025-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gattest_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankansweroption',
            options={'ordering': ['question', 'order', 'created_at'], 'verbose_name': 'Вариант ответа (Банк)', 'verbose_name_plural': 'Варианты ответа (Банк)'},
        ),
        migrations.AddField(
            model_name='bankansweroption',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
