# Generated by Django 5.2.4 on 2025-10-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gattest_school_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gattest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='gattest',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gat_tests', to='core.schoolclass', verbose_name='Класс'),
        ),
    ]
