# Generated by Django 5.2.4 on 2025-11-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bankansweroption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gattest',
            name='is_published_for_students',
            field=models.BooleanField(default=False, verbose_name='Опубликовать как Past Paper?'),
        ),
        migrations.CreateModel(
            name='DifficultyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('easy_percent', models.PositiveIntegerField(default=30, verbose_name='% Легких')),
                ('medium_percent', models.PositiveIntegerField(default=40, verbose_name='% Средних')),
                ('hard_percent', models.PositiveIntegerField(default=30, verbose_name='% Сложных')),
                ('school_class', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_rules', to='core.schoolclass', verbose_name='Класс (Параллель)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_rules', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Правило сложности',
                'verbose_name_plural': 'Правила сложности',
                'constraints': [models.UniqueConstraint(fields=('school_class', 'subject'), name='unique_rule_per_class_subject')],
            },
        ),
    ]
