# Generated by Django 5.2.4 on 2025-09-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_class', to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
    ]
