# Generated by Django 5.2.4 on 2025-10-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gattest_school_alter_gattest_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarters', to='core.academicyear', verbose_name='Учебный год'),
        ),
    ]
