# Generated by Django 5.2.4 on 2025-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gattest_is_published_for_students_difficultyrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='image_width',
            field=models.CharField(default='100%', max_length=20, verbose_name='Ширина изображения'),
        ),
    ]
