# Generated by Django 5.2.4 on 2025-10-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_quarter_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='gat_info',
        ),
        migrations.AddField(
            model_name='gattest',
            name='subjects',
            field=models.ManyToManyField(to='core.subject', verbose_name='Предметы в тесте'),
        ),
    ]
