# Generated by Django 5.2.4 on 2025-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teachernote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_class', 'last_name_ru', 'first_name_ru']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name (eng.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Имя (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_tj',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ном (точ.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name (eng.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_tj',
            field=models.CharField(blank=True, max_length=100, verbose_name='Насаб (точ.)'),
        ),
    ]
