# Generated by Django 5.2.4 on 2025-10-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_subject_gat_info_gattest_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gattest',
            options={'ordering': ['-test_date', 'test_number', 'day'], 'verbose_name': 'GAT Тест', 'verbose_name_plural': 'GAT Тесты'},
        ),
        migrations.AddField(
            model_name='gattest',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'День 1'), (2, 'День 2')], default=1, verbose_name='День GAT'),
        ),
    ]
