# Generated by Django 5.2.4 on 2025-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gattest_options_gattest_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_per_school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название предмета'),
        ),
    ]
