# Generated by Django 5.2.4 on 2025-10-11 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('GENERAL_DIRECTOR', 'Генеральный директор'), ('DIRECTOR', 'Директор'), ('EXPERT', 'Эксперт'), ('TEACHER', 'Учитель'), ('HOMEROOM_TEACHER', 'Классный руководитель'), ('STUDENT', 'Ученик')], max_length=50, null=True, verbose_name='Роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото')),
                ('homeroom_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher_profile', to='core.schoolclass', verbose_name='Класс (для Кл. руководителя)')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.school', verbose_name='Школа (для Учителя)')),
                ('schools', models.ManyToManyField(blank=True, related_name='directors', to='core.school', verbose_name='Доступные школы (для Директора)')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.student', verbose_name='Студент (для Ученика)')),
                ('subjects', models.ManyToManyField(blank=True, related_name='experts_and_teachers', to='core.subject', verbose_name='Предметы (для Эксперта/Учителя)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
