# Generated by Django 5.2.4 on 2025-09-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0006_schoolclass_homeroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, help_text='Обязательно для роли Ученик', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student', verbose_name='Карточка Ученика'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Генеральный Директор'), ('SCHOOL_DIRECTOR', 'Директор Школы'), ('TEACHER', 'Учитель'), ('STUDENT', 'Ученик'), ('EXPERT', 'Эксперт по предмету')], default='TEACHER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Обязательно для Директора и Учителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Обязательно для Эксперта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='Предмет экспертизы'),
        ),
    ]
