# Generated by Django 5.2.4 on 2025-10-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0008_alter_gattest_options_gattest_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='homeroom_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher_profile', to='core.schoolclass', verbose_name='Классное руководство'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('GENERAL_DIRECTOR', 'Генеральный директор'), ('DIRECTOR', 'Директор'), ('EXPERT', 'Эксперт'), ('TEACHER', 'Учитель'), ('HOMEROOM_TEACHER', 'Классный руководитель'), ('STUDENT', 'Ученик')], default='TEACHER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.school', verbose_name='Школа (для Учителя)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='director_profiles', to='core.school', verbose_name='Доступ к школам (для Директора)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.student'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject', verbose_name='Предметы (для Учителя/Эксперта)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
