# Generated by Django 5.2.4 on 2025-10-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_student_alter_userprofile_photo_and_more'),
        ('core', '0008_alter_student_options_remove_student_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_schools',
            field=models.ManyToManyField(blank=True, help_text='Выберите школы, к которым у директора будет дополнительный доступ', related_name='accessible_by', to='core.school', verbose_name='Дополнительный доступ к школам'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('SCHOOL_DIRECTOR', 'Директор Школы'), ('TEACHER', 'Учитель'), ('STUDENT', 'Ученик'), ('EXPERT', 'Эксперт по предмету')], default='TEACHER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Обязательно для Директора и Учителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', verbose_name='Основная школа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
