# Generated by Django 5.2.4 on 2025-10-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Супер-администратор'), ('GENERAL_DIRECTOR', 'Генеральный директор'), ('DIRECTOR', 'Директор'), ('EXPERT', 'Эксперт'), ('TEACHER', 'Учитель'), ('HOMEROOM_TEACHER', 'Классный руководитель'), ('STUDENT', 'Ученик')], default='TEACHER', max_length=20, verbose_name='Роль'),
        ),
    ]
